version: "3"
services:
    nginx:
        platform: linux/amd64
        image: nginx:alpine
        container_name: nonamez-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - nonamez

    php:
        platform: linux/amd64
        build:
            args:
                user: nonamez
                uid: 1000
            context: .
            dockerfile: docker-compose/php/Dockerfile
        container_name: nonamez-php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - nonamez

    db:
        platform: linux/amd64
        image: mariadb:10.5.8
        container_name: nonamez-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - nonamez

    node:
        platform: linux/amd64
        image: node:latest
        container_name: nonamez-node
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        tty: true
    
networks:
    nonamez:
        driver: bridge