#!/bin/sh
echo "Running docker custom entrypoint"
umask 0002

role=${CONTAINER_ROLE:-app}

if [ "$role" = "app" ]
then
    echo "Supervisor files setting for APP"

    rm -f /etc/supervisor/conf.d/php-supervisor-local.conf
    rm -f /etc/supervisor/conf.d/php-supervisor.conf
else
    echo "Supervisor files setting for Supervisor"
    
    if [ "$APP_ENV" = "local" ]
    then
        rm -f /etc/supervisor/conf.d/php-supervisor.conf
    else
        rm -f /etc/supervisor/conf.d/php-supervisor-local.conf
    fi
fi

echo "Composer install"

if [ "$APP_ENV" = "local" ] || [ "$APP_ENV" = "testing" ]
then
    cd /var/www && composer install
else
    cd /var/www && composer install --no-dev
fi

if [ "$role" = "app"  ]
then
    while ! mysqladmin ping -h"$DB_HOST" --silent; do
        echo "Waiting for mysql"
        sleep 1
    done

    echo "Run migration"
    php artisan migrate --force    
fi

chmod -R 777 /var/www/storage/log
chmod -R 777 /var/www/storage/framework
chmod -R 777 /var/www/bootstrap/cache

if [ "$APP_ENV" != "local" ]
then
  chown www-data.www-data /var/www -R
fi

echo "Ready to go online"

exec /usr/local/bin/docker-php-entrypoint php-fpm -F $@