version: '3.9'
services:
    nginx:
        container_name: ${APP_NAME}-nginx
        build:
            context: ./nginx
        ports:
            - 8081:80
        env_file:
            - .env
        volumes:
            - ../src/public:/var/www/public
        depends_on:
            - php

    php:
        container_name: ${APP_NAME}-php
        build:
            context: ./php
        working_dir: /var/www
        volumes: 
            - ../src:/var/www
        env_file:
            - .env
            - ../src/.env
        depends_on:
            - mysql
            #- postgres

    php-supervisor:
        container_name: ${APP_NAME}-php-supervisor
        image: ${APP_NAME}-php
        working_dir: /var/www
        volumes: 
            - ../src:/var/www
        environment:
            - CONTAINER_ROLE=supervisor
        env_file:
            - .env
            - ../src/.env
        depends_on:
            - mysql
            #- postgres

    mysql:
        container_name: ${APP_NAME}-mysql
        image: mariadb:10.7
        ports:
            - 3307:3306
        env_file:
            - .env
        volumes:
            - ./mysql/data:/var/lib/mysql
            
    mysql-test:
        container_name: ${APP_NAME}-mysql-test
        image: mariadb:10.7
        env_file:
            - .env

    # postgres:
    #     container_name: ${APP_NAME}-postgres
    #     image: postgres:9
    #     ports:
    #         - 5432:5432
    #     env_file:
    #         - .env
    #     volumes:
    #         - ./postgres/data:/var/lib/postgresql/data
    #         - ./postgres/imports:/home/postgresql

    # postgres-test:
    #     container_name: ${APP_NAME}-postgres-test
    #     image: postgres:9
    #     env_file:
    #         - .env

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        ports:
            - 6379:6379
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s

    mailhog:
        container_name: ${APP_NAME}-mailhog
        image: mailhog/mailhog:latest
        ports:
            - 8025:8025
            - 1025:1025
