version: '3.9'
services:
    nginx:
        container_name: ${APP_NAME}-nginx
        build:
            context: ./nginx
        ports:
            - 8081:80
        env_file:
            - .env
        volumes:
            - ../src/public:/var/www/public
        depends_on:
            - php

    php:
        container_name: ${APP_NAME}-php
        image: ${APP_NAME}-php
        build:
            context: ./php
        working_dir: /var/www
        volumes: 
            - ../src:/var/www
        env_file:
            - .env
            - ../src/.env
        depends_on:
            - mariadb

    php-supervisor:
        container_name: ${APP_NAME}-php-supervisor
        image: ${APP_NAME}-php
        working_dir: /var/www
        volumes: 
            - ./php:/var/www
        environment:
            - CONTAINER_ROLE=supervisor
        env_file:
            - .env
            - ../src/.env
        depends_on:
            - mariadb
            - redis
            - mariadb-test

    mariadb:
        container_name: ${APP_NAME}-mariadb
        image: mariadb:10.7
        ports:
            - 3307:3306
        env_file:
            - .env
        volumes:
            - ./mysql/data:/var/lib/mysql
            
    mariadb-test:
        image: mariadb:10.7
        env_file:
            - .env

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        ports:
            - 6379:6379
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s

    mailhog:
        container_name: ${APP_NAME}-mailhog
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025